name: vvvvv_frontend
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_route: ^1.0.2
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  hooks_riverpod: ^0.14.0+1
  json_annotation: ^4.0.1
  logger: ^1.0.0
  mocktail: ^0.1.1
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^2.0.0-beta1

dev_dependencies:
  auto_route_generator: ^1.0.2
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2
  hive_generator: ^1.0.1
  json_serializable: ^4.1.0
  lint: ^1.0.0
  retrofit_generator: ^2.0.0-beta3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/