name: Build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: dart-lang/setup-dart@v1
      
      - name: install dependencies
        uses: steebchen/flutter@v1.1.0
        with:
         args: pub get
         
      - name: generate localication
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub run easy_localization:generate -f keys -S "assets/translations" -O "lib/localization" -o "locale_keys.g.dart"
         
      - name: run build runner
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub run build_runner build --delete-conflicting-outputs
          
      - name: Analyze project source
        run: dart analyze

      - name: run tests
        uses: steebchen/flutter@v1.1.0
        with:
          args: test

      - name: build apk
        uses: steebchen/flutter@v1.1.0
        with:
          args: build apk --release
